In [6]:
import numpy as np

#Generating the random 5x5 array
X = np.random.rand(5, 5)  #generates random values between 0 and 1
print("Original X:\n", X)

#Compute mean and standard deviation
mean_X = X.mean()
std_X = X.std()
print("\nMean of X:", mean_X) #Print the Mean
print("Standard Deviation of X:", std_X) #Print the Standard Deviation

#Use the given normalization formula
X_normalized = (X - mean_X) / std_X
print("\nNormalized X:\n", X_normalized) #Print the Normalized X

#Save the normalized ndarray as X_normalized.npy
np.save("X_normalized.npy", X_normalized)
print("\nNormalized data has been saved as 'X_normalized.npy'")

Original X:
 [[0.41285248 0.91417265 0.54087676 0.94721665 0.07492484]
 [0.707402   0.85468117 0.77829158 0.59672289 0.27347176]
 [0.36097637 0.80440561 0.78581754 0.90145956 0.15760627]
 [0.23659094 0.1580355  0.54914297 0.01630884 0.50893529]
 [0.61087732 0.8867319  0.8423654  0.00766122 0.88016881]]

Mean of X: 0.5523078540892592
Standard Deviation of X: 0.30730316240959576

Normalized X:
 [[-0.45380389  1.17754987 -0.03719809  1.28507887 -1.55345949]
 [ 0.50469429  0.9839577   0.73537717  0.14453166 -0.90736487]
 [-0.62261477  0.82035524  0.75986751  1.13617999 -1.28440455]
 [-1.02737933 -1.28300781 -0.0102989  -1.74420272 -0.14113935]
 [ 0.1905918   1.0882545   0.94388077 -1.77234307  1.06689745]]

Normalized data has been saved as 'X_normalized.npy'


In [1]:
import numpy as np

#Generate squares of the first 100 positive integers
numbers = np.arange(1, 101)   #array of numbers from 1 to 100
squares = numbers ** 2        #square each number

#Reshape into 10x10 ndarray or matrix
A = squares.reshape(10, 10)
print("10x10 ndarray (A):\n", A) #Print the array

#Find elements divisible by 3
div_by_3 = A[A % 3 == 0]
print("\nElements divisible by 3:\n", div_by_3) #Print the elements divisible by 3

# Step 4: Save results to 'div_by_3.npy'
np.save("div_by_3.npy", div_by_3)
print("\nArray of elements divisible by 3 saved as 'div_by_3.npy'")

10x10 ndarray (A):
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]

Array of elements divisible by 3 saved as 'div_by_3.npy'
